import {closeIcon} from './icons.js';
import {animate} from 'motion';
import {createCartAPI,applicableDiscountCodes} from './cart-api.js';
import {findVariantForOption} from './product-options.js';
let installed=false,cart={items:[]},api;
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const emit=(name,detail)=>document.dispatchEvent(new CustomEvent(name,{detail}));
const error=(root,message)=>{if(root?.isConnected===false&&root.dataset.cartSection)root=$(`[data-cart-section="${CSS.escape(root.dataset.cartSection)}"]`)||document;const target=$('[data-commerce-error]',root)||$('[data-commerce-error]');if(target)target.textContent=message;};
const rootURL=()=>window.Shopify?.routes?.root||'/';
const openCart=()=>emit('kw:cart-open');
async function addWithLoading(button,id,quantity=1){button.classList.add('kw-add-loading');button.setAttribute('aria-busy','true');try{await api.add(id,quantity);openCart();}finally{button.classList.remove('kw-add-loading');button.removeAttribute('aria-busy');}}
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const spring={type:'spring',stiffness:380,damping:28};
async function refreshCart(next){
 cart=next;const sectionNodes=$$('[data-cart-content]');const ids=[...new Set(sectionNodes.map(n=>n.dataset.cartSection))];
 if(ids.length){const url=new URL(location.href);url.searchParams.set('sections',ids.join(','));const response=await fetch(url,{credentials:'same-origin'});if(!response.ok)throw Error('Unable to refresh bag');const sections=await response.json();for(const node of sectionNodes){const html=sections[node.dataset.cartSection];if(!html)continue;const doc=new DOMParser().parseFromString(html,'text/html');const replacement=$('[data-cart-content]',doc);if(replacement){node.replaceWith(replacement);emit('kw:content-updated',{root:replacement});}}}
 syncCart();emit('kw:cart-updated',{cart});
}
function syncCart(){
 $$('[data-discount-codes]').forEach(container=>{container.replaceChildren();for(const code of applicableDiscountCodes(cart)){const chip=document.createElement('span');chip.className='inline-flex items-center gap-1 rounded-full bg-rust/10 px-2.5 py-1 text-[10px] font-medium text-rust';chip.append(document.createTextNode(code));const remove=document.createElement('button');remove.type='button';remove.dataset.removeDiscount=code;remove.setAttribute('aria-label',`${container.dataset.removeLabel} ${code}`);remove.className='ml-0.5 text-rust/70 hover:text-rust disabled:opacity-40';remove.innerHTML=closeIcon;remove.classList.add('text-[8px]');chip.append(remove);container.append(chip);}});
 syncPriceBuckets();
 $$('[data-cart-count]').forEach(el=>{const count=Number(cart.item_count)||0;el.textContent=count>9?'9+':String(count);el.hidden=count===0;});
 $$('[data-product-card]').forEach(card=>{const present=cart.items.some(i=>String(i.product_id)===card.dataset.productId);const button=$('[data-card-action]',card);if(button){($('[data-card-label]',button)||button).textContent=present?button.dataset.viewLabel:button.dataset.available==='false'?button.dataset.outOfStockLabel:button.dataset.addLabel;button.disabled=!present&&button.dataset.available==='false';button.dataset.inCart=String(present);}const badge=$('[data-card-badge]',card),discount=$('[data-card-discount]',card);if(badge)badge.hidden=!present;if(discount)discount.hidden=present;});
 $$('[data-product-section]').forEach(updateProduct);
}
function updateProduct(section){
 const variants=JSON.parse($('[data-variants]',section).textContent),select=$('[data-variant-select]',section),variant=variants.find(v=>String(v.id)===select.value)||variants[0];if(!variant)return;
 const present=cart.items.some(i=>String(i.variant_id)===String(variant.id));section.dataset.inCart=String(present);
 const money=n=>new Intl.NumberFormat(document.documentElement.lang||'en-IN',{style:'currency',currency:section.dataset.currency||'INR',maximumFractionDigits:n%100?2:0}).format(n/100);
 $('[data-product-price]',section).textContent=money(variant.price);const compare=$('[data-product-compare]',section);compare.hidden=variant.compare_at_price<=variant.price;compare.textContent=money(variant.compare_at_price);
 const discount=$('[data-product-discount]',section);discount.hidden=compare.hidden;discount.textContent=compare.hidden?'':`${discount.dataset.saveLabel} ${Math.round((variant.compare_at_price-variant.price)/variant.compare_at_price*100)}%`;
 $$('[data-selected-option]',section).forEach(label=>{label.textContent=variant.options?.[Number(label.dataset.selectedOption)]||'';});
 $$('[data-option-value]',section).forEach(button=>{const index=Number(button.dataset.optionIndex),selected=variant.options?.[index]===button.dataset.optionValue;const available=variants.some(candidate=>candidate.available&&candidate.options?.[index]===button.dataset.optionValue&&candidate.options.every((value,otherIndex)=>otherIndex===index||value===variant.options[otherIndex]));button.disabled=!selected&&!available;button.setAttribute('aria-pressed',String(selected));button.classList.toggle('bg-rust',selected);button.classList.toggle('text-white',selected);button.classList.toggle('text-strong-coffee',!selected);button.classList.toggle('kw-unavailable-size',!available);});
 const quantity=$('[name="quantity"]',section);if(variant.max!==null)quantity.max=variant.max;else quantity.removeAttribute('max');quantity.value=Math.max(1,Math.min(Number(quantity.value)||1,variant.max??Infinity));
 const stock=$('[data-stock]',section);stock.textContent=variant.available&&variant.max>0&&variant.max<=5?stock.dataset.stockTemplate.replace('{quantity}',variant.max):'';
 const add=$('[data-product-add]',section),buy=$('[data-product-buy]',section);add.disabled=buy.disabled=!variant.available;($('[data-action-label]',add)||add).textContent=section.dataset.justAdded==='true'?add.dataset.addedLabel:present?add.dataset.inLabel:add.dataset.addLabel;($('[data-action-label]',buy)||buy).textContent=present?buy.dataset.checkoutLabel:buy.dataset.buyLabel;const bagIcon=$('[data-add-icon]',add),checkIcon=$('[data-in-icon]',add);if(bagIcon)bagIcon.hidden=present;if(checkIcon)checkIcon.hidden=!present;add.classList.toggle('bg-dark-chocolate',present);add.classList.toggle('bg-white',!present);add.classList.toggle('text-rust',!present);add.classList.toggle('text-white',present);$('[data-product-quantity]',section).hidden=present;$('[data-sold-out]',section).hidden=variant.available;
}
async function busy(scope,work){if(scope.dataset.commerceBusy)return;scope.dataset.commerceBusy='true';const controls=$$('button,input,select',scope);const state=controls.map(n=>n.disabled);controls.forEach(n=>n.disabled=true);error(scope,'');try{await work();}catch(e){error(scope,e.message);}finally{delete scope.dataset.commerceBusy;controls.forEach((n,i)=>n.disabled=state[i]);syncCart();}}
let navigationController,searchTimer;
async function navigateSection(url,selector,{replace=false,searchOnly=false}={}){
 navigationController?.abort();const controller=new AbortController();navigationController=controller;const current=$(selector);if(!current)return;
 const id=current.dataset.collectionSection||current.dataset.searchSection;const requestURL=new URL(url,location.href);requestURL.searchParams.set('section_id',id);current.setAttribute('aria-busy','true');
 try{const response=await fetch(requestURL,{signal:controller.signal});if(!response.ok)throw Error(current.dataset.errorMessage);const text=await response.text();if(controller.signal.aborted)return;const doc=new DOMParser().parseFromString(text,'text/html'),replacement=$(selector,doc);if(!replacement)throw Error(current.dataset.errorMessage);if(searchOnly){$('[data-search-results]',current).replaceWith($('[data-search-results]',replacement));}else {for(const modal of $$('[data-modal]',current)){if(!modal.hidden)await window.KW?.closeModal?.(modal);}if(controller.signal.aborted)return;current.replaceWith(replacement);}history[replace?'replaceState':'pushState']({},'',url);initializeCommerce(document);emit('kw:content-updated',{root:searchOnly?current:replacement});}catch(e){if(e.name!=='AbortError')error(current,e.message);}finally{current.removeAttribute('aria-busy');}
}
function search(value,replace=true){const url=new URL(location.href);url.searchParams.delete('page');url.searchParams.set('type','product');if(value.trim())url.searchParams.set('q',value.trim());else url.searchParams.delete('q');return navigateSection(url,'[data-search-section]',{replace,searchOnly:true});}
function collectionURL(form){const url=new URL(form.action,location.href);url.searchParams.delete('page');for(const [key,value]of new FormData(form))if(value!=='')url.searchParams.append(key,value);return url;}
function syncFilterActions(scope=document){for(const aside of $$('[data-filter-form]',scope).map(form=>form.closest('aside')).filter(Boolean)){const params=new URL(location.href).searchParams;const applied=[...params.keys()].some(key=>key.startsWith('filter.')&&params.getAll(key).some(Boolean));const clear=$('[data-filter-clear]',aside),apply=$('[data-filter-apply]',aside);delete aside.dataset.filterDirty;if(clear)clear.hidden=!applied;if(apply)apply.hidden=true;}}
function markFilterChanged(form){const aside=form?.closest('aside');if(!aside)return;aside.dataset.filterDirty='true';const apply=$('[data-filter-apply]',aside);if(apply)apply.hidden=false;}
function setPriceBucket(button){const aside=button.closest('aside'),form=$('[data-filter-form]',aside),minInput=$('[data-price-min-input]',form),maxInput=$('[data-price-max-input]',form);if(!form||!minInput||!maxInput)return;const active=button.getAttribute('aria-pressed')==='true';minInput.value=active?'':button.dataset.priceMin;maxInput.value=active?'':button.dataset.priceMax||'';$$('[data-price-min]',aside).forEach(item=>{const selected=item===button&&!active;item.setAttribute('aria-pressed',String(selected));for(const name of ['border-rust','bg-rust','text-white'])item.classList.toggle(name,selected);for(const name of ['border-strong-coffee/20','bg-white','text-strong-coffee/85'])item.classList.toggle(name,!selected);});markFilterChanged(form);}
function clearCollectionFilters(){const url=new URL(location.href),section=$('[data-collection-section]');url.pathname=section?.querySelector('[data-filter-form]')?.getAttribute('action')||url.pathname;url.searchParams.delete('page');for(const [key]of [...url.searchParams])if(key.startsWith('filter.'))url.searchParams.delete(key);navigateSection(url,'[data-collection-section]');}
function syncPriceBuckets(){const params=new URL(location.href).searchParams;$$('[data-price-min]').forEach(button=>{const aside=button.closest('aside'),form=$('[data-filter-form]',aside),minInput=$('[data-price-min-input]',form),maxInput=$('[data-price-max-input]',form);const min=aside?.dataset.filterDirty==='true'&&minInput?minInput.value:params.get('filter.v.price.gte');const max=aside?.dataset.filterDirty==='true'&&maxInput?maxInput.value:params.get('filter.v.price.lte');const active=min===button.dataset.priceMin&&max===(button.dataset.priceMax||'');button.setAttribute('aria-pressed',String(active));for(const name of ['border-rust','bg-rust','text-white'])button.classList.toggle(name,active);for(const name of ['border-strong-coffee/20','bg-white','text-strong-coffee/85'])button.classList.toggle(name,!active);});}
export function findVariantImageIndex(variants,id,images){const image=variants.find(v=>String(v.id)===String(id))?.image;if(!image)return 0;const path=value=>{try{return new URL(value,'https://shop.invalid').pathname;}catch{return value;}};return Math.max(0,images.findIndex(url=>path(url)===path(image)));}
function initGallery(section){const gallery=$('[data-gallery]',section);if(!gallery||gallery.dataset.ready)return;gallery.dataset.ready='true';const thumbs=$$('[data-gallery-thumb]',gallery);let active=0,scale=1,x=0,y=0;const canvas=$('[data-zoom-canvas]',section),zoom=$('[data-zoom-image]',section);if(!canvas||!thumbs.length)return;
 const transform=()=>{scale=Math.min(5,Math.max(1,scale));if(scale===1)x=y=0;zoom.style.transform=`translate(${x}px,${y}px) scale(${scale})`;};
 let swap=0,mainAnimation;const track=$('[data-gallery-track]',section);
 const show=(index,scrollTrack=true)=>{active=(index+thumbs.length)%thumbs.length;const item=thumbs[active],main=$('#ProductMainImage',section);if(main){const token=++swap;mainAnimation?.stop();const enter=()=>{if(token!==swap)return;main.src=item.dataset.image;main.removeAttribute('srcset');main.alt=item.dataset.alt;if(!reduced())mainAnimation=animate(main,{opacity:[0,1],y:[8,0]},{duration:.3,ease:[.22,1,.36,1]});};if(main.dataset.shown&&!reduced()){mainAnimation=animate(main,{opacity:0,y:-4},{duration:.2,ease:'easeIn'});mainAnimation.then(enter);}else enter();main.dataset.shown='true';}if(scrollTrack&&track){track.scrollLeft=active*track.clientWidth;}zoom.src=item.dataset.image;zoom.alt=item.dataset.alt;scale=1;x=y=0;transform();$$('[data-gallery-counter],[data-lightbox-counter]',section).forEach(n=>n.textContent=`${String(active+1).padStart(2,'0')} / ${String(thumbs.length).padStart(2,'0')}`);thumbs.forEach((b,i)=>{b.setAttribute('aria-current',String(i===active));b.classList.toggle('outline-rust',i===active);});};
 section.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.hasAttribute('data-gallery-thumb'))show(Number(t.dataset.galleryThumb));if(t.hasAttribute('data-lightbox-thumb'))show(Number(t.dataset.lightboxThumb));if(t.hasAttribute('data-gallery-step'))show(active+Number(t.dataset.galleryStep));if(t.hasAttribute('data-gallery-open')){if(t.dataset.galleryOpen!=='')show(Number(t.dataset.galleryOpen));const trigger=document.createElement('button');trigger.dataset.openModal='product-zoom';document.body.append(trigger);trigger.click();trigger.remove();}if(t.hasAttribute('data-zoom-step')){scale+=Number(t.dataset.zoomStep);transform();}if(t.hasAttribute('data-zoom-reset')){scale=1;transform();}});
 track?.addEventListener('scroll',()=>{const index=Math.round(track.scrollLeft/track.clientWidth);if(index!==active)show(index,false);},{passive:true});
 canvas.style.touchAction='none';canvas.addEventListener('wheel',e=>{e.preventDefault();scale+=e.deltaY<0?.2:-.2;transform();},{passive:false});canvas.addEventListener('dblclick',e=>{if(e.target===zoom){scale=scale>1?1:2;transform();}});const pointers=new Map();let distance=0;
 canvas.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});distance=0;});canvas.addEventListener('pointermove',e=>{const previous=pointers.get(e.pointerId);if(!previous)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(distance)scale*=d/distance;distance=d;}else if(scale>1){x+=e.clientX-previous.x;y+=e.clientY-previous.y;}transform();});['pointerup','pointercancel'].forEach(event=>canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);distance=0;}));document.addEventListener('keydown',e=>{if($('[data-modal="product-zoom"]',section)?.hidden)return;if(e.key==='ArrowRight')show(active+1);if(e.key==='ArrowLeft')show(active-1);});const variants=JSON.parse($('[data-variants]',section).textContent);show(findVariantImageIndex(variants,$('[data-variant-select]',section).value,thumbs.map(t=>t.dataset.image)));section.addEventListener('kw:variant-image',e=>{show(findVariantImageIndex([{id:'selected',image:e.detail}],'selected',thumbs.map(t=>t.dataset.image)));});
}
function animateGuide(modal){
 if(reduced())return;
 const panel=$('[data-guide-panel]:not([hidden])',modal);if(!panel)return;
 $$('[data-guide-row]',panel).forEach((row,index)=>animate(row,{opacity:[0,1],y:[12,0]},{duration:.45,delay:.05+index*.05,ease:[.22,1,.36,1]}));
 $$('[data-guide-panel="measure"] > div:last-child > p',modal).forEach((row,index)=>animate(row,{opacity:[0,1],y:[12,0]},{duration:.45,delay:.05+index*.05,ease:[.22,1,.36,1]}));
 $$('svg path',panel).forEach((path,index)=>{animate(path,{pathLength:[0,1],opacity:[0,1]},{duration:index===1?1:index===0?.7:.6,delay:[0,.15,.6,.8,1][index]||0,ease:[.22,1,.36,1]});});
 $$('svg text',panel).forEach((label,index)=>animate(label,{opacity:[0,1],x:[5,0]},{duration:.4,delay:.9+index*.2}));
}
document.addEventListener('kw:modal-open',event=>{if(event.detail.id==='size-guide')animateGuide(event.detail.modal);});
export function initializeCommerce(root=document){
 $$('[data-product-section]',root).forEach(section=>{updateProduct(section);initGallery(section);});syncCart();syncFilterActions(root);if(installed)return;installed=true;
 api=createCartAPI({root:rootURL(),errorMessage:$('[data-cart-content]')?.dataset.errorMessage,onUpdate:refreshCart});api.read().then(next=>{cart=next;syncCart();}).catch(()=>{});
 if($('[data-collection-section]')&&!new URL(location.href).searchParams.has('sort_by')){const url=new URL(location.href);url.searchParams.set('sort_by','best-selling');navigateSection(url,'[data-collection-section]',{replace:true});}
 document.addEventListener('submit',e=>{const form=e.target;if(form.matches('[data-card-form]')){e.preventDefault();const button=$('[data-card-action]',form);if(button.dataset.inCart==='true'){openCart();return;}busy(form.closest('[data-product-card]'),()=>addWithLoading(button,Number(form.elements.id.value)));}
 if(form.matches('[data-product-form]')){e.preventDefault();const section=form.closest('[data-product-section]'),buy=e.submitter?.hasAttribute('data-product-buy');if(section.dataset.inCart==='true'){if(buy)location.href=rootURL()+'checkout';else openCart();return;}const id=Number(form.elements.id.value),quantity=Number(form.elements.quantity.value);busy(section,()=>addWithLoading(e.submitter||$('[data-product-add]',section),id,quantity));}
 if(form.matches('[data-discount-form]')){e.preventDefault();const code=form.elements.discount.value.trim();if(!code)return;busy(form.closest('[data-cart-content]'),async()=>{const codes=applicableDiscountCodes(cart);const result=await api.discount([...new Set([...codes,code])]);if(result.discount_codes?.some(c=>c.code.toLowerCase()===code.toLowerCase()&&!c.applicable))error($('[data-cart-content]'),$('[data-cart-content]')?.dataset.invalidDiscount);});}
 if(form.matches('[data-search-form]')){e.preventDefault();clearTimeout(searchTimer);search(form.elements.q.value);}
 if(form.matches('[data-filter-form]')){e.preventDefault();navigateSection(collectionURL(form),'[data-collection-section]');}});
 document.addEventListener('input',e=>{if(e.target.matches('[data-search-form] [name="q"]')){clearTimeout(searchTimer);navigationController?.abort();searchTimer=setTimeout(()=>search(e.target.value),350);}});
 document.addEventListener('change',e=>{const target=e.target;if(target.matches('[data-sort]')){const url=new URL(location.href);url.searchParams.set('sort_by',target.value);url.searchParams.delete('page');navigateSection(url,'[data-collection-section]');}if(target.matches('[data-filter-form] input[type="checkbox"]'))markFilterChanged(target.form);if(target.matches('[data-variant-select],[data-product-form] [name="quantity"]'))updateProduct(target.closest('[data-product-section]'));});
 document.addEventListener('click',e=>{const summary=e.target.closest('[data-product-details] summary');if(summary){e.preventDefault();const details=summary.parentElement,body=summary.nextElementSibling,closing=details.open;if(!closing)details.open=true;const height=body.scrollHeight;if(reduced()){details.open=!closing;return;}body.style.overflow='hidden';animate(body,{height:closing?[height,0]:[0,height],opacity:closing?[1,0]:[0,1]},{duration:.35,ease:[.22,1,.36,1]}).then(()=>{details.open=!closing;body.style.height='';body.style.overflow='';});animate($('span',summary),{rotate:closing?0:180},{duration:.3,ease:[.22,1,.36,1]});return;}const target=e.target.closest('button,a');if(!target)return;
 const line=target.closest('[data-cart-line]'),scope=target.closest('[data-cart-content]');if(line&&(target.hasAttribute('data-cart-delta')||target.hasAttribute('data-cart-remove')||target.hasAttribute('data-cart-variant'))){e.preventDefault();busy(scope,()=>target.hasAttribute('data-cart-variant')?api.swap(line.dataset.cartLine,Number(target.dataset.cartVariant)):api.change(line.dataset.cartLine,target.hasAttribute('data-cart-remove')?0:Number(line.dataset.quantity)+Number(target.dataset.cartDelta)));}
 if(target.hasAttribute('data-remove-discount'))busy(scope,()=>api.discount(applicableDiscountCodes(cart).filter(code=>code!==target.dataset.removeDiscount)));
 if(target.hasAttribute('data-option-value')){if(!reduced())animate(target,{scale:[.94,1]},spring);const section=target.closest('[data-product-section]'),select=$('[data-variant-select]',section),variants=JSON.parse($('[data-variants]',section).textContent),variant=findVariantForOption(variants,select.value,Number(target.dataset.optionIndex),target.dataset.optionValue);if(variant){select.value=variant.id;updateProduct(section);const url=new URL(location.href);url.searchParams.set('variant',variant.id);history.replaceState({},'',url);if(variant.image)section.dispatchEvent(new CustomEvent('kw:variant-image',{detail:variant.image}));}}
 if(target.hasAttribute('data-product-delta')){const section=target.closest('[data-product-section]'),quantity=$('[name="quantity"]',section);quantity.value=Math.max(1,Math.min(Number(quantity.value)+Number(target.dataset.productDelta),Number(quantity.max)||Infinity));updateProduct(section);}
 if(target.hasAttribute('data-price-min')){e.preventDefault();setPriceBucket(target);const aside=target.closest('aside');if(aside)aside.dataset.filterDirty='true';}
 if(target.hasAttribute('data-filter-clear')){e.preventDefault();clearCollectionFilters();}
 if(target.matches('[data-collection-link], [data-collection-section] [data-pagination] a')){e.preventDefault();navigateSection(target.href,'[data-collection-section]');}
 if(target.hasAttribute('data-search-term')||target.hasAttribute('data-clear-search')){const value=target.dataset.searchTerm||'';const input=$('[data-search-form] [name="q"]');if(input){input.value=value;clearTimeout(searchTimer);search(value);input.focus();}}
 if(target.hasAttribute('data-guide-tab')){const modal=target.closest('[data-modal]');$$('[data-guide-panel]',modal).forEach(p=>p.hidden=p.dataset.guidePanel!==target.dataset.guideTab);$$('[data-guide-tab]',modal).forEach(b=>{b.classList.toggle('text-rust',b===target);b.setAttribute('aria-selected',String(b===target));});const indicator=$('[data-guide-indicator]',modal);if(indicator)animate(indicator,{x:target.offsetLeft},{type:'spring',stiffness:380,damping:30,duration:reduced()?0:undefined});animateGuide(modal);}
 if(target.hasAttribute('data-guide-unit')){if(!reduced())animate(target,{scale:[.9,1]},{type:'spring',stiffness:400,damping:30});const modal=target.closest('[data-modal]');$$('[data-inches]',modal).forEach(n=>n.textContent=target.dataset.guideUnit==='cm'?`${Math.round(Number(n.dataset.inches)*2.54)} cm`:`${n.dataset.inches}″`);$$('[data-guide-unit]',modal).forEach(b=>{b.setAttribute('aria-pressed',String(b===target));b.classList.toggle('text-white',b===target);});const pill=$('[data-guide-unit-indicator]',modal);if(pill)animate(pill,{x:target.offsetLeft-2,width:target.offsetWidth},{type:'spring',stiffness:400,damping:30,duration:reduced()?0:undefined});animateGuide(modal);}
 });
 window.addEventListener('popstate',()=>{const product=$('[data-product-section]');if(product){const id=new URL(location.href).searchParams.get('variant');if(id)$('[data-variant-select]',product).value=id;updateProduct(product);}if($('[data-collection-section]'))navigateSection(location.href,'[data-collection-section]',{replace:true});if($('[data-search-section]')){const input=$('[data-search-form] [name="q"]');input.value=new URL(location.href).searchParams.get('q')||'';search(input.value);}});
}
